### ISSUE TITLE
NPA layer optimering

### ISSUE THREAD

**Issue by arnigeir** [arnigeir/App4Sea#13]
NPA kmz skráin er ca 1M en unzippuð (kml) er hún 3.5M   þe meir en 3x þjöppun.   Þetta er samt  óþarflega stór skrá og væri hægt að optimizera með því t.d. að fækka punktum í strandlínu landa.

**Comment by arnigeir** [comment]
Þurfum að styðja þjappaðar kml skrár.   Legg til að við prófum það áður en við leggjum vinnu í að lagfæra þessa skrá.

**Comment by ThorsteinnHelgi** [comment]
Lets þetta nú inn sem kmz í stað kml.
