### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by arnigeir** [arnigeir/App4Sea#7]
Skilgreina menukerfi
grúppa saman atriđi og ákveđa virkni og útlit

**Comment by ThorsteinnHelgi** [comment]
See information under Map Comments in One Note.

**Comment by arnigeir** [comment]
Það er töluverð falin vinna þarna í þessu skjali

https://onedrive.live.com/view.aspx?ref=button&Bsrc=SMIT&resid=81F3B7E8D11FE475!20488&cid=81f3b7e8d11fe475&app=OneNote&authkey=!An44r4erBzEsdtM

Til að hægt sé að skoða/filtera þekjur eftir t.d. löndum eða svæðum þarf að tengja item í þekjum við viðkomandi land og svæði.   Það er ekki gefið að td. land sé eins skráð í mismunandi kml skrám og getur verið allur gangur á því.    Ef það er krafa að almennt geta filterað eftir löndum og svæðum þarf að parsa xml skrárnar og koma í gagnagrunn ásamt linkum í þau atriði (metadata) sem á að flokka/filtera eftir.   Þetta er talsverð vinna og betra að byrja á þessu strax í stað þess að bíða og halda áfram að henda inn kmz skrám sem erfitt er að vinna með.

Það eru komnir linkar í td hafnir (norskar) og skipaumferð og veður (marine).  Hvernig er staðan á að skrá App4Sea verkefnið sem notanda ?

Það eru mörg atr þarna sem virðast ekki vera með skilgreindan source.  Hvenær er planað að koma þessum gögnum inn í kerfið.

**Comment by ThorsteinnHelgi** [comment]
Sæll 

Er ekki til lib til að vinna með XMLið í Java og sem sé um að breyta því í object? Sé ekki að það sé sniðugt að við förum að parsa skrárnar. 

Ég þarf að fara að skila inn fleiri lögum, en við þurfum að hafa birtingu gagna eins og hitakorta og upplýsingaglugga fyrir punkta í lagi. 

Ég sá ekki nýju hlekkina. 

Eigum við að koma okkur upp reglulegum fundum, t.d. kl. 16 á mánudögum? 

Kv. Þ

**Comment by arnigeir** [comment]
Sæ..

Jú það eru til ýmsir xml parsersar í Java og ég held við komumst varla hjá
því að parsa xml ef það á að vera hægt að filtera þessi gögn sem eru í xml
formi. Sýnist líka að það þurfi þekkingu á kml formatti til að gera þetta
því mér sýnist strúktúrinn mismunandi milli xml skrá.   Skoðaðu t.d NPA
skrána og mismun milli Færeyja og Finnlands.   Í tilfelli Færeyja þá er
eitt Placemark tag sem inniheldur allar upplýsingar um landið en í tilfelli
Finnlands þá er Folder tag og mörg Placemark tög.   Hvert placemark
skilgreinir eh svæði og er með sitt Extended data tag í stað eins í
tilfelli Færeyja.   Eina sem skilur þetta að er Name tagið sem getur
auðveldlega verið mismunandi milli KML skráa (þe frá mismunandi aðilum).
 Sé enga "country codes" eða ID sem hægt er að nota þvert á öll gögn.+


Hver er hugmyndin með "svæði".  Skilgreinir svæði lönd eða er það
skilgreint með hnitapunktum ?

Prófaðu að skoða nokkrar af þeim kml skrám sem við erum þegar komnir með og
ath hvort það sé hægt að parsa þær þannig að hægt sé að fliltera eftir
landi/svæði eða öðru án þess að gera sér parser fyrir hverja skrá.  Ef
slíkt er krafa (þe að hægt sé að brjóta þekju niður eða gera leit í þekju)
þá þurfum alltaf XML parser

Athugaðu að flestar gagnaveitur bjóða upp á REST API sem skila JSON (amk
þeir linkar sem ég skoðaði í skjalinu þínu).   Við þurfum sem sé að geta
unnið bæði með XML og JSON. Það væri betra að geta haldið sig við eitt
gagnaformat í openlayers - annað er tvöföld vinna.

Ertu með dæmi um hitakort sem ég get skoðað ?   Það væri gott að geta
fengið slíkt fljótlega til að skoða hvernig við komum slíkum gögnum á
kortið.

Ég er að vinna í að birta upplýsingaglugga fyrir þau kml sem við erum með.

Hvaða nýju hlekki ertu að vísa í ?  Ath að ég er ekki búinn að uppfæra
serverinn.  Sendi þér póst þegar ég uppfæri.

Mánudagar ganga því miður ekki - ég er á reglulegum fundum milli 17-18 sem
vilja oft dragast.

Ég fer núna að skipta yfir á hjólið og reikna með að vera á hjóli flesta
daga þannig að fundarstaðurinn verður helst að vera í hjólafæri (frá LSH
eða OR).  Helst þá hafa fundinn 17:30 svo ég nái að komast á staðinn :)





kv
Árni.





2018-04-08 11:54 GMT+00:00 Þorsteinn Helgi Steinarsson <
notifications@github.com>:

**Comment by ThorsteinnHelgi** [comment]
Komið með jstree
